### ISSUE TITLE
CARICOOS layers not updating

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#153]
...for maybe a year??  No data for any timestamp that I choose.

**Comment by kknee** [comment]
@kbailey-noaa all of the CariCOOS sources were changed or unavailable.  Assuming we should reach out about updating?

**Comment by kbailey-noaa** [comment]
@kknee Yes, please.

**Comment by kknee** [comment]
@kbailey-noaa CariCOOS provided new endpoints for all models.  It will take the EDS team sometime to work through all these changes.  Suggest we remove CariCOOS from this milestone.

**Comment by kknee** [comment]
@kbailey-noaa we have the waves coming into EDS staging (so not view-able for you yet). But Looks like there was an outage on March 28th, then the data came back on the 29th, but with a filename of YYYYMMDD0000.nc, instead of YYYYMMDD1200.nc. We've changed the URL to point to the 0000 files, and will report back after letting it run for a bit.  

Changing file names with out notifying us will cause issues, not sure how to address this with CariCOOS

**Comment by kknee** [comment]
@kbailey-noaa winds are also in progress, note that CariCOOS did not provide us with an endpoint for currents, so those will not be included in this issue.

**Comment by kbailey-noaa** [comment]
@kknee Thanks for the update.  I'm not aware of a forum for service change updates among data providers... Maybe we can urge people to use the IOOS_Tech listserv for that. @mwengren are you aware of a forum where people can announce changes to services? Would IOOS_Tech be appropriate?

**Comment by mwengren** [comment]
It could be, I feel like there was an effort to do this before (I recall deleting a noaa.gov email group that IOOS had created for some point in order to do this, but I don't think it was the most effective way to go about it).  Too specialized and never really was used.  

So, I agree ioos_tech is probably the best option we have, but of course it requires people to actually post notices.  Another question is how granular a notice such as this should be, no doubt the RAs will be making minor changes to their services all the time that they might not think require an announcement anywhere (probably much more often the case than something they might be tempted to announce).

**Comment by kknee** [comment]
@mwengren even small changes (e.g. to a variable name) can impact the harvest.  Always a challenge to figure out the best way to communicate these.  Our current approach is a bit too reactive - but essentially we monitor the services and EDS developers get notified when a source is down.

**Comment by kknee** [comment]
@kbailey-noaa CARICOOS SWAN is back live on production.  Winds are coming along nicely. Doesn't look like CARICOOS is running a regional hydro model at the moment - they have a subset of RTOFS on their TDS.
