### ISSUE TITLE
Slider range not reflected in time-series plot

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#201]
@kknee @Bobfrat 

I changed the slider range to "past 7 days" but the TS plot doesn't update and still shows default +/- 2 days.  I can only get the plot to change to past 7 days if I drag the time slider to a date out of range of the TS window.  

![image](https://user-images.githubusercontent.com/11823385/66329607-ca015b80-e8fc-11e9-9e55-b9a1c0978e89.png)

**Comment by kknee** [comment]
@kbailey-noaa the length of the timeseries has never changed, those quick links just change the timeseries range. 

we've been exploring an update to this functionality so we'll keep the EDS Model view in mind as a candidate for update when ready.

**Comment by Bobfrat** [comment]
Just for background, the time-series plots was always limited to a 5 day range to protect us from users that turn on a bunch of layers, set the range to 2 years and want to see a plot. That's a big burden on the system. I'm in favor of having the plot match the time slider range because that's intuitive, but I'd prefer to set limits on the time slider range if that's the case.

**Comment by kbailey-noaa** [comment]
@Bobfrat Got it, thanks! I think we can just keep it as is.  I'm not hearing any complaints from users.
