### ISSUE TITLE
Time-series data gaps

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#216]
Present gaps in time-series data as actual gaps. Don't connect the data in the plot. e.g. see below - 

![image](https://user-images.githubusercontent.com/11823385/79766764-6964c980-82f6-11ea-8369-d33ac72bc474.png)

**Comment by Bobfrat** [comment]
@kbailey-noaa I assume you are talking about observation data rather than model data? The operational models ideally wont have gaps unless we encounter issues with the harvest. For observation data this can get tricky as every sensor/instrument/platform may sample at different frequencies. 

So we either need to store the expected sampling frequency of every parameter and every station or we come up with some global setting that seems to work best. For example, we could say any gap > 12 hrs shouldn't have a line connecting data points. That may cover most cases but if we have sensors that sample once a day then the entire time series could be more of a scatter plot. What do you think?

**Comment by kbailey-noaa** [comment]
@Bobfrat I meant both (that pic was from WCOFS) but I thought it would just be a plotting 'feature' that could be changed.  I didn't realize it's more involved.  I'm going to close this b/c I feel like it isn't necessary/worth the hassle.  I prefer lines to scatter plots.
