### ISSUE TITLE
Some obs layers need info button

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#37]
The following obs layers are missing an info button:

CO-OPS, CBIBS, NDBC and Partner, NDBC...profiling, UCSD HF Radar (1 km, 2km, 6km).

**Comment by kknee** [comment]
@kbailey-noaa these all have abstracts now.  The NDBC Partner Profiling stations probably needs a different abstract than the standard NDBC one.  Thoughts on how to word this one instead of: 

"The National Data Buoy Center (NDBC) is a part of the National Oceanic and Atmospheric Administration's (NOAA) National Weather Service (NWS). NDBC designs, develops, operates, and maintains a network of data collecting buoys and coastal stations. The NBDC is located in southern Mississippi as a tenant at the John C. Stennis Space Center, a National Aeronautics and Space Administration (NASA) facility."

**Comment by kknee** [comment]
@kbailey-noaa can you check out what we have and let us know what you think?

**Comment by kbailey-noaa** [comment]
CBIBS:  It's owned by the NOAA Chesapeake Bay Office.  Should weave this in.
CO-OPS:  Pare down, include mention of NOAA.  Don't need the first sentence.  Can start with "The Center for... (CO-OPS)...is the authoritative source..."
NDBC & Partner stations:  The bit about where NDBC is located can be removed.  
NDBC partner profiling stations - agree, this must be different from NDBC's abstract.  "Oil and Gas industry Acoustic Doppler Current Profiler data are collected at drilling platforms throughout the Gulf of Mexico.  These real-time ADCP data have been released to NDBC for public distribution of current profile information throughout the Gulf." 
NERRS:  "For historical data click data source below." -- ??  Remove this.
HF Radar abstracts in general don't mention the owner (MARACOOS, UCSD, USWC) - need to define UCSD and USWC (but don't need to define MARACOOS).  
West Coast HFR USWC -- "With a HF-radar system an entire current field can be generated every fifteen minutes. (as shown in the above figure)."-- remove this.

**Comment by kknee** [comment]
@kbailey-noaa edited your comment above to check off what is done.  For NERRS, we need to keep that statement per our agreement with them for harvesting data.

**Comment by kbailey-noaa** [comment]
Got it.

**Comment by kknee** [comment]
@kbailey-noaa all of the changes above have been made
