### ISSUE TITLE
Add data access links in the (i) popup window for NDBC and CO-OPS

### ISSUE THREAD

**Issue by dpsnowden** [asascience-open/IOOS-EDS#45]

**Comment by kknee** [comment]
adding links to the data access points that we use, see below.  @dpsnowden let me know if you had something else in mind.

NDBC: http://sdf.ndbc.noaa.gov/sos/
CO-OPS: https://tidesandcurrents.noaa.gov/api/

**Comment by dpsnowden** [comment]
I was hoping to advertise the standardized data access options for CO-OPS as opposed to their proprietary API (which is probably very useful BTW).  The THREDDS. ERDDAP, and SOS links are available [here](https://opendap.co-ops.nos.noaa.gov/)

How is the map populated?  With their API or with one of the above options?

**Comment by kknee** [comment]
ready for review on dev: http://dev.oceansmap.com/eds/#

**Comment by kknee** [comment]
also - co-ops was updated to the SOS link per @dpsnowden

**Comment by kbailey-noaa** [comment]
The API might be better for populating the map.  I was hoping to include the station name along with the 7 digit identifier, and it doesn't look like that parameter is available through their SOS.  

I reviewed the changes and the CO-OPS and NDBC abstracts now include links to their SOS pages.

**Comment by kknee** [comment]
@kbailey-noaa i'm unclear whether we're all set here or not?  Should we switch back to the API?

**Comment by kbailey-noaa** [comment]
@kknee Ok, I'm confused.  I thought we were using the SOS this whole time to show the CO-OPS observed data values in the station pop up.  Your Jan 9 note above indicated API - were you using API or SOS?  Assuming we were using SOS, I'm seeing that their API is better so I'll open a separate github issue to request that we point to the API to display the data values in the popup.  

However, this github issue is focused on the 'data access' link in the information window.  
Derrick's point was that we should be providing links to the standard services - THREDDS, ERDDAP, SOS, where possible, in all cases.  In this case (CO-OPS observations), we should include ERDDAP and SOS (their obs are not provided via THREDDS) and also the link to the API.  So 3 total.  

This changes the nature of how we display the "data access" link in that information box.  Instead of just the one link called "data access" can we provide multiple links named after the service?  e.g. "ERDDAP", "SOS", "API" etc.

**Comment by kknee** [comment]
@kbailey-noaa my question earlier today was solely relative to the data access link -  we switched to SOS and I was unclear from your Jan 25 message if we should go back to API.  Can we settle on one for now to settle this issue and open a separate issue for revamping how 'Data Access' links work in general?

P.S. we are using the SOS feed to populate the map.  So good that you posted a separate issue to switch.

**Comment by kbailey-noaa** [comment]
Got it.  Stay with SOS for the link.  I'll close this issue.

**Comment by dpsnowden** [comment]
Sorry, now  I'm confused.  Are we talking about data access link or data access links (plural)?  I was hoping  that we would be able to have multiple links for various types of access.

**Comment by kknee** [comment]
we were talking about singular and now we're talking about plural, so this issue was closed in favor of #63
