### ISSUE TITLE
Adding NANOOS Models

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#73]
@kknee
@emiliom - I want to follow up with NANOOS on some of the general questions asked about EDS (what it is, etc).  Sounds like you weren't able to join the demo last year, but [here](https://ioos.noaa.gov/data/access-ioos-data/#model) is some information. 

As follow-up from the NANOOS DMAC webinar (4/17) I examined NANOOS models in the [NVS Data Explorer](http://nvs.nanoos.org/Explorer) and the IOOS Catalog.  We currently have OSU ROMS (salinity, currents, water temp) and plan to make NANOOS part of the layer name for better attribution.

Here are other NANOOS models/layers we could include in the EDS, plus questions about endpoints:

1) CMOP Columbia - Water temp and salinity.  
https://data.ioos.us/dataset/cmop-virtual-columbia-river-selfe-f333

2) OSU Waves
We have a WW3 model covering the West Coast but it looks like this OSU version has a higher resolution.  The NVS shows a merged overlay of the NCEP low-res NE Pacific domain and the OSU high-res Oregon domain.  It's this high-res domain I think we should include.
Emilio - do you have an endpoint?

**Comment by emiliom** [comment]
Thanks, @kbailey-noaa! I did see the EDS Model Viewer at the IOOS DMAC meeting last year (June), and have looked at it on my own once or twice; but not recently.

Regarding NANOOS models, the place to start is what we make available via registered THREDDS services. As you said, the CMOP Columbia is available -- but note the url you pasted has an extra "3"! It should be this: https://data.ioos.us/dataset/cmop-virtual-columbia-river-selfe-f33

We're open to suggestions for changing the THREDDS service metadata to better propagate attribution and any other important or helpful information, for both CMOP Columbia and OSU ROMS. And to improve standard compliance, discoverability, etc.

OSU Waves is a special case. It's not NANOOS funded, and I believe we're not able (or allowed?) to distribute it via THREDDS at this time. So, let's put it aside. We can discuss offline.

Another NANOOS model that @kknee, myself and the model PI have been in discussions about is a ROMS implementation labelled ["LiveOcean"](http://nvs.nanoos.org/Explorer?action=oiw:model:LiveOcean:details). We don't have it on THREDDS yet, but want to. @kknee is already making progress on integrating it into EDS.

**Comment by emiliom** [comment]
For reference: LiveOcean model is being discussed in #29

**Comment by emiliom** [comment]
I'm adding a slightly tangential comment here rather than open a new issue. It's about a NANOOS model that's currently on the EDS Model Viewer, **"NANOOS West Coast (OSU ROMS)"**. I see that EDS has a capability to have a description of the model that goes with the "more info" (i) button, but this model doesn't have any. Can we provide one, and can it include a url or two for users to be able to navigate back to the source?

**Comment by kknee** [comment]
@emiliom yes, we'd love to have a description for this model, thanks!

**Comment by emiliom** [comment]
> we'd love to have a description for this model, thanks!

Great. Will follow up.

**Comment by emiliom** [comment]
@kknee, here's a description for the **"NANOOS West Coast (OSU ROMS)"** model. I compiled it from existing descriptions and links we had. At some time in the near future I'll engage the PI and other NANOOS folks to look it over and refine it. For now, I just want to make the improvement of going from NO description to a reasonable description! I realize this is a bit long; let me know if you have hard limits and it needs to be pared down.

-------------------------------------------

These experimental nowcast and forecast fields are produced by the [Oregon Washington Coastal Ocean Forecast System](http://ingria.coas.oregonstate.edu/rtdavow/), a computer model of the Oregon and Washington coastal ocean circulation from the [Coastal Ocean Modeling and Data Assimilation Group](http://ingria.coas.oregonstate.edu) at Oregon State University. These forecasts are updated daily at 12:15 pm. The [model data](http://ona.coas.oregonstate.edu:8080/thredds/catalog.html?dataset=OCOS) was generated as part of an academic research project, and the principal investigator Dr. Alexander Kurapov (kurapov@coas.oregonstate.edu) asks to be informed of intent for scientific use and appropriate acknowledgement given in any publications arising therefrom. The data is provided free of charge, without warranty of any kind.

An important part of the input to the model is a 5-day record of winds over the Oregon coast. This record is derived from an operational weather forecast model, and covers the past two days and the forecast for the coming three days. Each day, the model takes this record and its previous estimate of the ocean state from two days before, and combines it with a mathematical representation of the physical principles for fluid motion. The result is, each day, a 3-day nowcast and forecast record. To improve accuracy of forecasts, the model ocean estimate is optimally combined with recent observations. Initial conditions for the forecasts are constrained by assimilation of surface currents measured remotely by high-frequency (HF) radars installed along the coast and satellite derived sea surface temperature fields.

**Comment by kknee** [comment]
thanks @emiliom.  It goes in a scrollable box, so we'll get it in and then we can all review what it looks like.

**Comment by kknee** [comment]
@emiliom the abstract for OSU ROMS is up

**Comment by emiliom** [comment]
> @emiliom the abstract for OSU ROMS is up

Yes, I saw it over a week ago. Thanks!

**Comment by emiliom** [comment]
> would like to add CMOP SELFE to EDS

Great, thanks @kbailey-noaa! I'm cc'ing @cseaton from CMOP, who is the technical contact person for the CMOP THREDDS end point. @kknee, please work with him (via this github issue or a separate one, as you see fit) to get the appropriate model variables on the test EDS, and at that point we can refine the model layer name and compose attribution text, as we have done for the two other NANOOS models.

**Comment by cseaton** [comment]
hi @kknee and @kbailey-noaa, what information do you need to proceed with including the CMOP SELFE f33 forecast in the EDS? For variables names, the relevant ones are probably surface_salt, bottom_salt, surface_temp, bottom_temp, and elev. avg_salt and avg_temp would also be reasonable ones to include. The IOOS catalog already has a link to the WMS server: http://amb6400b.stccmop.org:8080/ncWMS2/

**Comment by emiliom** [comment]
Thanks @cseaton. Worth pointing out that the IOOS catalog entry also includes the correct OPeNDAP endpoint.

**Comment by kbailey-noaa** [comment]
@cseaton @emiliom @kknee We'll need an 'abstract' describing the model and output.  If you go to eds.ioos.us and hover over the Currents "NOAA San Francisco SFBOFS" layer name and click the "i" you can see what kind of information (and length of text) we're looking for. Basically just a paragraph describing the model (doesn't need to be specific to that particular variable in Viewer, since we plan to eventually reorganize the table of contents by region). You can just submit that text through this github issue.

**Comment by emiliom** [comment]
Thanks @kbailey-noaa. We'll do that Monday or Tuesday. I've worked with @kknee previously to compose abstracts for the two other NANOOS models, so we're good, in terms of knowing what to shoot for :grinning:. We'll submit it through this github issue.

**Comment by emiliom** [comment]
@kbailey-noaa and @kknee Has there been progress on the integration of the CMOP Columbia Estuary SELFE model into EDS?

For the model layer name, our suggestion is "NANOOS Columbia Estuary (CMOP SELFE)"

And here's a draft for the abstract (thanks, @cseaton!):

The experimental nowcast and forecast fields displayed here from the CMOP Virtual Columbia River are produced by a computer model (SELFE) of the Columbia River estuary and the Oregon and Washington coastal ocean circulation, with a primary focus on the Columbia River estuary and the Columbia River plume. These forecasts are updated daily at 9:00 am. They are an experimental product intended for research use only. For more information, please visit the [CMOP Virtual Columbia River forecast](http://www.stccmop.org/datamart/virtualcolumbiariver/forecasts).

**Comment by kbailey-noaa** [comment]
@kknee @Bobfrat Do you have any updates on this?

**Comment by kknee** [comment]
@kbailey-noaa @emiliom I'll get you an update asap.

**Comment by kknee** [comment]
@kbailey-noaa @emiliom - we've got surface salinity and SST in EDS already, we'll grab the other variables and then add everything to OceansMap.

@emiliom @cseaton - do either of you have recommended ranges for display of variables?  Our default salinity looks good, but SST doesn't have much variation:

![image](https://user-images.githubusercontent.com/196868/32511485-dfc6ca20-c3c1-11e7-8ce5-2fda9e88c44a.png)

![image](https://user-images.githubusercontent.com/196868/32511492-e5a7e9ba-c3c1-11e7-9232-ea5ece4e9699.png)

**Comment by emiliom** [comment]
Thanks, @kknee -- looking great!

Re: SST range. Yeah, the default range of 0-32 will yield pretty bland results out in the PNW. @cseaton please comment on a better default, bearing in mind that I suspect they're looking for a range that will be reasonable throughout the year, not just right now.

**Comment by emiliom** [comment]
Sorry, forgot to comment: I think we were shooting for salinity and temp initially. @cseaton, are there other variable available on the THREDDS server that you'd recommend OR have concerns about?

**Comment by kknee** [comment]
@emiliom - looks like there were a few different levels for salinity and temp that we need to grab.  @cseaton also mentioned elev.  If you want to start with surface salinity and SST just LMK and we'll push those to OceansMap

**Comment by cseaton** [comment]
For temperature, I'd suggest 6-20. That won't always show much variability, but it covers most of the range of temperatures observed over the year (and only goes out of range for freshwater).

In addition to surface salinity and SST, I'd suggest bottom_temp and bottom_salt. I shouldn't have mentioned elev. We'd prefer not to display elevation for liability reasons.

**Comment by emiliom** [comment]
@kknee, just following up on the status of ingesting the NANOOS CMOP SELFE model with the updated metadata @cseaton and I have provided. I don't see the model on the live EDS Viewer, so I assume it's not live yet? Though come to think it (and maybe tangentially), I wonder if there's any connection between the NANOOS CMOP SELFE and the "NOAA Columbia River (CREOFS)" already on the EDS; that model is also a SELFE model. @cseaton, do you know anything about that?

**Comment by kbailey-noaa** [comment]
@emiliom I think Kelly is on leave but the CMOP SELFE is currently in the dev EDS though isn't live yet.  So it appears we're successfully ingesting/displaying the data but haven't released it to production.

@kknee FYI - I was comparing the CMOP SELFE and CREOFS salinity data in dev and discovered a time offset of 5 hours.  It looks like one of the layers is in the wrong time zone.

**Comment by emiliom** [comment]
Thanks for the update @kbailey-noaa 

> FYI - I was comparing the CMOP SELFE and CREOFS salinity data in dev and discovered a time offset of 5 hours. It looks like one of the layers is in the wrong time zone.

@cseaton when you have some time could you comment on the CREOFS model and its relationship to CMOP SELFE? It'd be interesting to know.

**Comment by emiliom** [comment]
@kknee I think I heard you're back from leave (and BTW, Congratulations!). If so, I wanted to see if we can complete (releasing to live) the CMOP SELFE integration we started last year.

I'll be on vacation next week, but @cseaton can answer any questions.

BTW, @cseaton, can you address the comments from @kbailey-noaa asked on January 2 (above)? Basically, comment on the relationship between the CREOFS model and CMOP SELFE.

Thanks, all.

**Comment by kknee** [comment]
@emiliom 

I think the last issue is to figure out if we have a time offset issue, e.g. 

![image](https://user-images.githubusercontent.com/196868/38443461-ba2def78-39b9-11e8-8e37-dfc23419cc8c.png)

**Comment by cseaton** [comment]
CREOFS is a NOAA run model that was developed in cooperation with CMOP based on our experience with the CMOP SELFE model.

@kknee can you tell me more about how you are generating that image? I'd like to investigate the question of the time offset, but I am not sure how to look at these results or at the CREOFS model results that EDS is using.

5 hours is a really strange offset to have between the two models.

**Comment by kknee** [comment]
@cseaton 

1. go to http://dev.oceansmap.com/eds/
2. scroll down in the TOC and turn off Global HYCOM
3. use the filter input box at the top of the TOC to search for salinity
4. turn on CREOFS and CMOP
5. zoom into Columbia river
6. click anywhere on the map where the two datasets overlap to generate the time series plot.

(note CREOFS is a bit out of date in EDS right now, you may have to go back in time a day or so to get a full plot)

**Comment by cseaton** [comment]
Comparing the results of the backend WMS server for the IOOS EDS:

http://coastmap.com/ecop/wms.aspx?styles=SST_USCG-Jet-0-33&elevation=0&format=image%2Fpng&ABOVEMAXCOLOR=extend&height=408&bbox=-13835904.708413897%2C5812309.849318942%2C-13797991.942384448%2C5827903.003089123&transparent=true&layers=CMOP_SALINITY&service=WMS&srs=EPSG%3A3857&request=GetMap&BELOWMINCOLOR=extend&width=992&version=1.1.1&time=2018-04-14T00:00:00Z

and the CMOP WMS server:
http://amb6400b.stccmop.org:8080/ncWMS2/wms?&STYLES=default-scalar/x-Rainbow&elevation=0&format=image%2Fpng&ABOVEMAXCOLOR=extend&height=408&bbox=-13835904.708413897%2C5812309.849318942%2C-13797991.942384448%2C5827903.003089123&transparent=true&LAYERS=f33_thredds/surface_salt&&service=WMS&srs=EPSG%3A3857&request=GetMap&BELOWMINCOLOR=extend&width=992&version=1.1.1&time=&exceptions=application%2Fvnd.ogc.se_xml&TIME=2018-4-14T08:00:00Z

and comparing both to a CMOP static plot of the same timestep:
http://www.stccmop.org/forecasts/f33/2018-103/images/isosal_mouth_surface/sal_mouth_surface_000172800.gif

It looks like the CMOP data has been incorrectly shifted in time on the coastmap server, with time in PST treated as time in GMT. The CMOP WMS is correctly representing the data in GMT and declaring it as such, so the error appears to me to be on the coastmap side.

I also compared a timeseries at a point downloaded from the IOOS EDS with the results of a GetTimeseries request to the CMOP WMS server:
http://amb6400b.stccmop.org:8080/ncWMS2/wms?REQUEST=GetTimeseries&LAYERS=f33_thredds/surface_salt&QUERY_LAYERS=f33_thredds/surface_salt&BBOX=-123.9557,46.2155,-123.9554,46.2156&SRS=EPSG%3A4326&FEATURE_COUNT=5&HEIGHT=600&WIDTH=750&X=636&Y=378&STYLES=default/default&VERSION=1.1.1&TIME=2018-4-12T00:00:00Z/2018-4-15T08:00:00Z&INFO_FORMAT=text/csv

but I was not able to get a GetTimeseries request to the coastmap WMS server to parse successfully, so my location of comparison is approximate and the results are not a perfect match. However, there is a distinctive feature at 2018-4-14 9:00Z in the CMOP data that aligns correctly with a matching feature in the IOOS EDS data for 2018-4-13 18:00 PDT, so that agrees with an incorrect interpretation of data acquired in PST being treated as data in GMT (4-14 9:00Z on the CMOP server becomes a false 4-14 1:00Z on the coastmap server, which is then translated to 4-13 18:00 PDT in the IOOS EDS).

There is also a weird issue in the IOOS EDS that seems unrelated but I thought I should note: when I select a time on the timeline in the IOOS EDS, the CMOP SELFE model and the NANOOS LiveOcean model (included as a tie-breaker for correct behavior) both show the same time as the timeline, but the CREOFS model shows a time that is 21 hours off from the time selected on the timeline. For instance, if I set the timeslider to: 2018-4-12 06:00 PDT, the IOOS EDS pulls the following image for CMOP SELFE: (note &time=2018-04-12T13:00:00Z)

http://coastmap.com/ecop/wms.aspx?layers=CMOP_SALINITY&styles=SST_USCG-winter-0-40&service=WMS&format=image%2Fpng&request=GetMap&ABOVEMAXCOLOR=extend&height=408&width=992&version=1.1.1&bbox=-13878059.729513168%2C5796984.225147767%2C-13726408.66539538%2C5859356.840228468&time=2018-04-12T13%3A00%3A00Z&exceptions=application%2Fvnd.ogc.se_xml&srs=EPSG%3A3857&BELOWMINCOLOR=extend&transparent=true

But it pulls the following image for CREOFS: (note&time=2018-04-13T10:00:00Z)
http://coastmap.com/ecop/wms.aspx?layers=NOSCREOFS_SALINITY&styles=SST_USCG-winter-0-40&service=WMS&format=image%2Fpng&request=GetMap&ABOVEMAXCOLOR=extend&height=408&width=992&version=1.1.1&bbox=-13878059.729513168%2C5796984.225147767%2C-13726408.66539538%2C5859356.840228468&time=2018-04-13T10%3A00%3A00Z&exceptions=application%2Fvnd.ogc.se_xml&srs=EPSG%3A3857&BELOWMINCOLOR=extend&transparent=true

The times displayed under the layer name in the IOOS EDS are consistent with the coastwatch calls, but not consistent with the timeslider selection.

Additionally, CREOFS images from the coastmap backend do not agree with CREOFS images from the CREOFS site:
Here is a CREOFS image for 2018-4-13 3:00 PDT:
https://tidesandcurrents.noaa.gov/ofs/creofs/model_graphics/CREOFS_crb_all_sa_now_201804130300.png
That should match the previous coastwatch image from 2018-04-13T10:00:00Z if coastwatch were handling CREOFS timestamps correctly.
I didn't investigate this as fully, but it looks like CREOFS has been shifted by 3 additional hours, so that 
https://tidesandcurrents.noaa.gov/ofs/creofs/model_graphics/CREOFS_crb_all_sa_now_201804130000.png
is a good match for the coastwatch image from 2018-04-13T10:00:00Z 

That CREOFS is mishandled by 3 hours (in addition to the weird 21 hour shift in the EDS interface) and CMOP is mishandled by 8 hours would explain the 5 hour shift you were seeing previously.

**Comment by kknee** [comment]
@cseaton thanks for the sleuthing and detailed description, we'll take a close look.

**Comment by emiliom** [comment]
@kknee at the DMAC meeting last month I forgot to ask you about the status of the CMOP SELFE model on the EDS Model Viewer. Has there been any progress since @cseaton provided his comprehensive assessment two months ago? Can you gives us an update? Thanks.

**Comment by kknee** [comment]
@cseaton @emiliom I believe the CMOP offset issue has been resolved.  Would one of you mind confirming?

Comparing the CMOP WMS server with the EDS WMS server for the same timestep:

http://amb6400b.stccmop.org:8080/ncWMS2/wms?&STYLES=default-scalar/x-Rainbow&elevation=0&format=image%2Fpng&ABOVEMAXCOLOR=extend&height=408&bbox=-13835904.708413897%2C5812309.849318942%2C-13797991.942384448%2C5827903.003089123&transparent=true&LAYERS=f33_thredds/surface_salt&&service=WMS&srs=EPSG%3A3857&request=GetMap&BELOWMINCOLOR=extend&width=992&version=1.1.1&time=&exceptions=application%2Fvnd.ogc.se_xml&TIME=2018-7-12T08:00:00Z

http://coastmap.com/ecop/wms.aspx?styles=SST_USCG-Jet-0-33&elevation=0&format=image%2Fpng&ABOVEMAXCOLOR=extend&height=408&bbox=-13835904.708413897%2C5812309.849318942%2C-13797991.942384448%2C5827903.003089123&transparent=true&layers=CMOP_SALINITY&service=WMS&srs=EPSG%3A3857&request=GetMap&BELOWMINCOLOR=extend&width=992&version=1.1.1&time=2018-07-12T08:00:00Z

Looking at the CREOFS issue now.

**Comment by cseaton** [comment]
@kknee I checked several times in both coastmap.com and CMOP, and the results are consistent, so it looks like the time offset issue is resolved. Thanks!

**Comment by emiliom** [comment]
Thanks, @kknee and @cseaton ! That's great news.

**Comment by kbailey-noaa** [comment]
@kknee I just want to make sure the CMOP SELFE abstract makes it in production for our upcoming release.  Here is the abstract text from @emiliom and @cseaton provided on Nov 2 2017 in this comment thread:

The experimental nowcast and forecast fields displayed here from the CMOP Virtual Columbia River are produced by a computer model (SELFE) of the Columbia River estuary and the Oregon and Washington coastal ocean circulation, with a primary focus on the Columbia River estuary and the Columbia River plume. These forecasts are updated daily at 9:00 am. They are an experimental product intended for research use only. For more information, please visit the [CMOP Virtual Columbia River forecast](http://www.stccmop.org/datamart/virtualcolumbiariver/forecasts).

**Comment by cseaton** [comment]
That abstract is still accurate. 
Thanks,
Charles

**Comment by emiliom** [comment]
Thank you, @kbailey-noaa. I see the model is now live (thanks @kknee !), but without the abstract.

@kknee feel free to close this issue once the abstract is live.

**Comment by kbailey-noaa** [comment]
@Bobfrat This seems like a quick fix to add the abstract, so keeping in 2.0.1.

**Comment by kbailey-noaa** [comment]
@emiliom The abstract has been uploaded.  Closing this issue. Thanks for your help!

**Comment by emiliom** [comment]
Looks great. Thanks so much @kbailey-noaa and @kknee for your help throughout the process.

**Comment by emiliom** [comment]
(reusing this closed issue -- please open a new one if you think it's worth it)
Checking out the "Theme" feature in the new Model Viewer today, I noticed that this model (CMOP SELFE) is not included in the NANOOS Theme. Please add it. Thanks.

**Comment by Bobfrat** [comment]
@emiliom should be set now
